### ISSUE TITLE
Support  ingress-nginx Canary ?

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix-ingress-controller#13]
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

**Comment by gxthrj** [comment]
> https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#canary

Yes, this is a useful annotation. At present, we support it by means of plug-ins. You can refer to the custom `canary plug-in` on the `route` or `service` through CRD (`ApisixRoute` & `ApisixService`).

The definition of annotation will be provided as a feature in the future, because we will rely on APISIX official canary plug-in support( @membphis ), and then we will provide both annotation and plugin ways .

**Comment by gxthrj** [comment]
Good news, the Apache APISIX community is discussing implementing a traffic-split plug-in, based on which canary can be implemented. 

The discuss mail list is https://lists.apache.org/thread.html/rf02dc53a4af5d98d2513d89256b47466934d129af06d0bdcdb49cc8e%40%3Cdev.apisix.apache.org%3E

**Comment by gxthrj** [comment]
As `traffic-split` has been merged in https://github.com/apache/apisix/pull/2935, we can support Canary now.
You can bind plugin in `ApisixRoute` or `ApisixService` to implement it.
