### ISSUE TITLE
feat: should follow desired error behavior of GatewayAPI

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix-ingress-controller#1325]
For example:

https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1alpha2/httproute_types.go#L228-L232

```
	// When a HTTPBackendRef is invalid, 500 status codes MUST be returned for
	// requests that would have otherwise been routed to an invalid backend. If
	// multiple backends are specified, and some are invalid, the proportion of
	// requests that would otherwise have been routed to an invalid backend
	// MUST receive a 500 status code.
```

**Comment by stillfox-lee** [comment]
I’d like to help.

**Comment by tao12345666333** [comment]
assigned, thanks @stillfox-lee

**Comment by stillfox-lee** [comment]
Hi, guys. I want to use APISIX [health check](https://apisix.apache.org/docs/apisix/health-check/) to implement this feature at first. But health check seems didn't meet the requirements. 

Here are health check logic:
> If there is no healthy node can be chosen, we will continue to access the upstream.

Which GatewayAPI need return 500 instead of access to the upstream.

> We won't start the health check when the upstream only has one node, as we will access it whether this unique node is healthy or not.

Should return 500 even though three is only one upstream which is invalid.

I don't know how I should implement this feature, can anyone give me some advice? Thanks.
