### ISSUE TITLE
bug: broken hash and sig for Ingress Controller 0.1.0

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix-ingress-controller#146]
The hash and sig links for the 0.1.0 Ingress Controller are broken.

**Comment by spacewander** [comment]
@gxthrj @tokers

**Comment by gxthrj** [comment]
@sebbASF Thanks for your reminder.
The reason is that the link on svn changed the file name (`rc2` was deleted).
 I restored file name and submitted to svn.
Thanks again.

**Comment by sebbASF** [comment]
As far as I can tell, the fix is incorrect.
Compare the hash and sig links for the other downloads on the page: http://apisix.apache.org/downloads/
and you will see that they use https://downloads.apache.org/apisix/..., and not 
https://www.apache.org/dyn/closer.cgi/apisix/...

Hashes and sigs must point to https://downloads.apache.org/, and must not use the mirror system

**Comment by gxthrj** [comment]
@sebbASF Got it. Fixed in https://github.com/apache/apisix-website/pull/123
Please take a look if you have time. Thanks.

**Comment by gxthrj** [comment]
@sebbASF Got it. Fixed in apache/apisix-website#125
Please take a look if you have time. Thanks.

**Comment by gxthrj** [comment]
Close this issue now, apache/apisix-website#125 has been merged. 
Thanks.

**Comment by gxthrj** [comment]
Hi, @sebbASF 

I have to reopen this issue , because there seems to be a problem with my previous modification.

In my In the [voting email](https://lists.apache.org/thread.html/r4d55e4f94bf46fb4edc9243c1db37b8cdaed850630d7637e20e4e6a6%40%3Cdev.apisix.apache.org%3E), I always use the name `0.1.0-rc2`.

But when I was updating svn, because of some understanding errors, I manually removed rc2, which caused sha512 to break.

In order to remedy my mistake, I think I should point all download links to the `0.1.0-rc2` address and delete the `0.1.0` download link.Ensure that hash and sig are consistent with the mailing list.
