### ISSUE TITLE
request help:  Does apisix ingress  support opentelementry plugin?

### ISSUE THREAD

**Issue by yangvipguang** [apache/apisix-ingress-controller#1848]
### Issue description

Does apisix ingress  support opentelementry plugin? 
version:  3.0
![image](https://github.com/apache/apisix-ingress-controller/assets/11416887/6a7e1949-a18c-4f89-84b1-577919ae228c)

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- 3.0
- your Kubernetes cluster version (output of kubectl version):
- 1.26
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
- rocky linux 9.2

**Comment by tao12345666333** [comment]
Yes, support. The APISIX Ingress controller can use any APISIX plugin, whether it is default or developed by the user. Moreover, there is no need to restart the APISIX Ingress.

Obviously, the problem you encountered is due to the fact that the plugin is disabled by default.

https://github.com/apache/apisix/blob/216e54dd99fb2eef7ebf681b78cce7d835b4bb9d/conf/config-default.yaml#L419

**Comment by yangvipguang** [comment]
@tao12345666333   thanks ,it works
