### ISSUE TITLE
Why it takes so long  for release 1.7 ,   Is there a planning date for for this release?

### ISSUE THREAD

**Issue by karl-chanel** [apache/apisix-ingress-controller#1890]

**Comment by moonming** [comment]
@tao12345666333 please take a look

**Comment by tao12345666333** [comment]
👌let me check

**Comment by tao12345666333** [comment]
https://github.com/apache/apisix-ingress-controller/milestone/16

As you can see, we have some unfinished jobs planned for v1.7.

I'll be pushing them aggressively, and once that's all over, then we'll release a new version. 

Also as an open source project, anyone can contribute to it.

If you expect a new version, please join in and help us solve related issues. Thanks!

I will close this issue, since it not related of any bug of this project.
