### ISSUE TITLE
does this project is dead?

### ISSUE THREAD

**Issue by daroga0002** [apache/apisix-ingress-controller#1931]
### Description

I see last release of this project was in December 2022. There are some new commits incoming but there is no new releases.

Does this mean this project is on dead path?

**Comment by acuteaura** [comment]
aside from the weird tag, we'd very much like a release cut for #1717

**Comment by tao12345666333** [comment]
No.

Thank you for your attention to this project. The project is still under active development, and the release schedule is determined based on the completion time of each milestone rather than a specific period.

https://github.com/apache/apisix-ingress-controller/milestone/16?closed=1
You can see here that we have completed many complex tasks and are currently approaching a state of completion.

**Comment by tao12345666333** [comment]
Thanks for your advice. 

We are also trying to make changes, but in fact, for the current actual situation, frequent releases bring a lot of maintenance costs. 
We will try our best to ensure the stability of the master branch code, so, under normal circumstances, anyone can build their own image based on the latest code of the master branch and deploy it.

Of course, if someone is willing to participate in the contribution, it is also possible to automatically build the image periodically and publish it

**Comment by tao12345666333** [comment]
v1.7 has been released. I will close this one. Thanks!
