### ISSUE TITLE
bug: etcd size increasing due to continuous ingress controller updates

### ISSUE THREAD

**Issue by connectashish5** [apache/apisix-ingress-controller#1984]
### Current Behavior

We are observing that etcd size is rapidly increasing, when we debugged it using etcd watch command we found that ingress controller is making continuous updates to keys in etcd at regular intervals inspite of there is no change to crd objects. Due to this we are running into disk space issues very frequently.

### Expected Behavior

Ingress controller should not update etcd keys unless there is a change to CRD.

### Steps to Reproduce

1. Deploy ingress-controller with 1 node.
2. Create APISIX CRDs.
3. Use etcd watch command to monitor traffic and continuous updates can be seen.

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Linux
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.7

**Comment by Revolyssup** [comment]
cc: @tao12345666333

**Comment by tao12345666333** [comment]
You can change the configuration item to stop ingress-controller intervals sync 

https://github.com/apache/apisix-ingress-controller/blob/master/conf/config-default.yaml

**Comment by indrekj** [comment]
We ran out of the default 2GB size limit and that took the cluster down. We've now set up autocompaction for etcd, hopefully, that will help in the future.

**Comment by hzhhong** [comment]
Encountering the same issue, it is because there are two apisix ingress controllers sharing apisix route and other crs. One of them has an abnormal etcd which leads to the failure of synchronizing apisix cr, continuously writing and updating the failed synchronization status to the status field. The other normal one updates the failure to normal, back and forth, resulting in frequent writes to etcd. The solution is to stop the apisix ingress controller associated with the abnormal etcd.
