### ISSUE TITLE
bug: namespaceSelector Unregister

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-ingress-controller#2058]
### Current Behavior

When I run kubectl label namespaces test env=informal, and then execute kubectl label namespaces test env-, the information of the "test" namespace still remains registered in Apisix without being unregistered.

### Steps to Reproduce

1

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
- Kubernetes cluster version (run `kubectl version`)
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)

**Comment by Revolyssup** [comment]
@jinjianming Do you mean if Apisix ingress is watching the namespaces with label `env=informal` then removing the label doesn't result in unwatching the namespace?

**Comment by Revolyssup** [comment]
@jinjianming Which information are you talking about here? Are you saying that the resources were not deleted?

**Comment by Revolyssup** [comment]
Any updates?

**Comment by jinjianming** [comment]
> @jinjianming Do you mean if Apisix ingress is watching the namespaces with label `env=informal` then removing the label doesn't result in unwatching the namespace?
Yes, when I delete the label of the namespace, there is still routing information for this namespace in the Apisix record

**Comment by Revolyssup** [comment]
@jinjianming I can confirm that the namespace is no longer watched after unlabelling. I think your concern is that the behaviour should be as follows:
Unwatching a namespace should result in deletion of Apisix resources in that namespace. Because that namespace is no longer watched, deleting the CRs also wouldn't have any effect because the namespace is not being watched. And the resources will never be deleted. Am I right?

**Comment by Revolyssup** [comment]
@jinjianming We have few ways around it.

1. Deleting all resources in that namespace: This might not be a good idea because the controller should not delete a resource. It should only be deleted by the user and controller should only react on it.
2. Giving a warning that the resources are still present: We can check for Apisix related CRs in that namespace and if there are still few CRs then we can put a warning log that XYZ resources are not deleted. And leave it to the user
3. Always watching for deletion, for add and update we keep the logic same but for deletion of APISIX CRs, we watch all the namespaces so that later on when user deleted the APISIX CR, the resources are deleted even when not being watched.

**Comment by Revolyssup** [comment]
Maybe we can deregister the apisix resources and update the status of apisix CRs for that resources explaining that these are now stale and no longer in effect. If we start watching the namespace again, we can remove the stale status and recreate the resources.
