### ISSUE TITLE
feat: add support for installing apisix ingress composite mode via helm chart

### ISSUE THREAD

**Issue by Padmabishek** [apache/apisix-ingress-controller#2130]
### Issue description

request help: I wanted to use apisix-composite architecture for an etcd-less apisix-ingress/gateway. Is it stable yet? When will be helm charts available for composite architecture? Is it safe to use for production? If not , when can we expect this feature to be stabilized. Thanks a lot for your help!

### Environment

- your apisix-ingress-controller version: 1.7.0
- your Kubernetes cluster version: v1.24.14

**Comment by Vacant2333** [comment]
@Revolyssup hello, can u help this

**Comment by Padmabishek** [comment]
@Revolyssup Any update on this ? Is this feature stabilized on 1.8.0 , I don't see anything regarding the feature in the release notes , please help

**Comment by Revolyssup** [comment]
@Padmabishek The architecture without etcd is experimental.

**Comment by Revolyssup** [comment]
@Padmabishek Helm supports deploying it. helm install ingress-apisix apisix/apisix-ingress-controller --create-namespace \
  -n ingress-apisix \
  --set config.apisix.serviceNamespace=ingress-apisix \
  --set config.etcdserver.enabled=false

**Comment by Vacant2333** [comment]
@Padmabishek looks like this issue was resoulve now? @Revolyssup how do u think, do we need update it to the docs?

**Comment by Revolyssup** [comment]
@kayx23 Will you take up this issue? Here maybe you can try installing the standalone mode via helm chart and document it in the doc.

**Comment by kayx23** [comment]
Let me circle back to this some time next week.

**Comment by Padmabishek** [comment]
Hi @kayx23,  Do we have any documentation available now ?

**Comment by kayx23** [comment]
Hello - not yet, haven't had the bandwidth for this thus far.

**Comment by Padmabishek** [comment]
I will try installation with below option and update my observations here.
helm install ingress-apisix apisix/apisix-ingress-controller --create-namespace
-n ingress-apisix
--set config.apisix.serviceNamespace=ingress-apisix
--set config.etcdserver.enabled=false

**Comment by ceelian** [comment]
@Padmabishek did this work as expected? Thx.

**Comment by kennycottrell** [comment]
> @Padmabishek did this work as expected? Thx.

Trying that command with apisix-ingress-controller chart 0.14.0 did not result in a working deployment. It correctly doesn't deploy etcd, but it also doesn't the apisix-gateway and the wait-admin init container just ends up printing the following forever:

waiting for apisix-admin
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'

**Comment by vortegatorres** [comment]
> Trying that command with apisix-ingress-controller chart 0.14.0 did not result in a working deployment. It correctly doesn't > deploy etcd, but it also doesn't the apisix-gateway and the wait-admin init container just ends up printing the following forever:
>
> waiting for apisix-admin
> nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'

I was able to successfully run the composite architecture using the [APISIX Helm chart version 2.10.0](https://github.com/apache/apisix-helm-chart/tree/apisix-2.10.0) and resolve the issue of an infinite loop by customizing the generated Kubernetes manifests from the Helm templates. Here's what I did:
- Enabled the embedded `etcd` server in the ingress controller configuration by setting `etcd.enabled=true`.
- Set the number of `etcd` replicas to 0 to prevent deploying a separate `etcd` cluster.
- In the default architecture:
  - The APISIX Gateway waits for `etcd` to become available.
  - The ingress controller waits for the APISIX Gateway admin to start (that is why you see the infinite loop of `waiting for apisix-admin`).
-  To break this circular dependency, I changed the behavior so that:
   - The APISIX Gateway now waits for the ingress controller on port 12379 instead (by modifying its initContainers).
   - I removed the initContainer from the ingress controller entirely, so it starts immediately.
- Exposed the ingress controller’s gRPC port 12379, allowing the APISIX Gateway to communicate with it.
- Configured the APISIX Gateway to use the ingress controller as its `etcd` host by pointing it to `http://apisix-ingress-controller.ingress-apisix.svc.cluster.local:12379` (or the equivalent in your namespace).

With these changes, both the APISIX Gateway and the ingress controller are able to start correctly, load custom route definitions, and function as they would in a traditional setup using `etcd`.

**Comment by tharwan** [comment]
@vortegatorres can you also share the code? 

Are there any plans to integrate this into the chart?

**Comment by tharwan** [comment]
Thanks for the quick reply. Maybe we will go with a manifest instead of the helm chart based on the sample one: https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/composite.yaml

**Comment by juzhiyuan** [comment]
Just for your reference, we are building a new Ingress Controller with detailed documentation, which will be released this month.

**Comment by juzhiyuan** [comment]
Hi @tharwan, we are actively working on it and testing it, and it's okay to assume that the release will be completed by the end of this month.
