### ISSUE TITLE
feat: As a user, I want to discover the external ip on the ApisixRoute, so that i can expose it trough automated dns

### ISSUE THREAD

**Issue by zs-ko** [apache/apisix-ingress-controller#2269]
### Description

As a user, I want to discover the external ip on the ApisixRoute CRD, so that i can expose it trough automated dns.

This would enable me to integrate external-dns against the custom CRD without requering access to the api and multiple round trips to the kubernetes api. 

This would also align the route crd to gateway routes and ingress spec.

**Comment by marcanpilami** [comment]
Hello, could it be possible to reopen this? `external-dns` has since added support for any type of CRD (in https://github.com/kubernetes-sigs/external-dns/blob/master/docs/sources/unstructured.md), and they provide an example with APISIX. However, this example uses a manual CNAME and not an A DNS entry - meaning this is not fully dynamic and error prone. 

A full support for thin functionality would be simply adding `status.loadBalancer.ingress.ip` to the CRD like for the ingress, as requested by the initial poster.
