### ISSUE TITLE
apisix custom nginx location dynamic configure

### ISSUE THREAD

**Issue by ly123-liu** [apache/apisix-ingress-controller#600]
apisix: 2.6
apisix-dashboard: 2.7
etcd: 3.5

apisix 是否在单个server 块中支持动态新增nginx location配置 或者其他指令呢？
apisix 在启动的配置中可通过snip支持，但是后续可能会存在新增的server name 有其他需求，apisix 能支持类似nginx-ingress ，不同的server可配置snip并且动态配置吗？

**Comment by gxthrj** [comment]
Due to the different implementation mechanisms of APISIX and Nginx, in APISIX ingress, we recommend using CRD (eg ApisixRoute Resource) to define routes (similar to the location in Nginx). 

In ApisixRoute resources, all routing rules are declared under `spec`, including some advanced configuration such as the canary, which is easier to understand, and conducive to verification, and ensures the correctness of the configuration.

In addition, using snippets is not easy to verify, and the more configuration, the more difficult it is to maintain.
So we do not plan to support snippet script in Apisix Ingress.

BTW， Please use English when discuss.

**Comment by tokers** [comment]
> apisix: 2.6
> apisix-dashboard: 2.7
> etcd: 3.5
> 
> apisix 是否在单个server 块中支持动态新增nginx location配置 或者其他指令呢？
> apisix 在启动的配置中可通过snip支持，但是后续可能会存在新增的server name 有其他需求，apisix 能支持类似nginx-ingress ，不同的server可配置snip并且动态配置吗？

Are there any special configurations that you have to use and are not easy to implement by APISIX primitives like Route and Plugins? If not so, you can just use the APISIX primitives.

**Comment by ly123-liu** [comment]
![image](https://user-images.githubusercontent.com/57338370/126257128-ba2a7ade-ecd4-4f73-8319-d93b69d7d63f.png)

yes, sometimes we need to update or add some static location , if else statement , max body size .. etc, how can i set this ? thanks

**Comment by tao12345666333** [comment]
> max body size

`client_max_body_size` can be set dynamically. You can just using `client-control` plugin to config it.

xref: https://github.com/apache/apisix/pull/4423

**Comment by tao12345666333** [comment]
@ly123-liu   we can support under the new architecture #610 

feel free to reopen it.
