### ISSUE TITLE
request help: I want to change upstream

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix-ingress-controller#847]
### Issue description

英语不好，直接中文了哈，我定义了个ApisixRoute 里面的 backend 是 test-server,  同时我也自定义了一个插件 用来计算一个请求要不要转发到其它domain,这个我怎么实现转发到其它domain呢？是更改up_conf配置吗

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
If I understand correctly, you probably need the ability of `proxy-rewrite` or `redirect` plugin?

You can refer to these cases

* https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/plugins/redirect.go
* https://github.com/apache/apisix-ingress-controller/blob/master/test/e2e/plugins/proxy_rewrite.go

**Comment by tokers** [comment]
It seems like your problem is about how to write a plugin to change some request behaviors, for this purpose, you need to read some source code of Apache APISIX, or checking our some other plugins.

The behaviors are just like the traffic split, you may also check out the traffic split plugin, or, you can define a few routes in `ApisixRoutes`, and assign different match rules for them.

**Comment by purekeeper** [comment]
@tokers   Thant's right, I'm reading the code and success do it ,thanks!
